(setq a 10) 
(setq b 20) 
(format t "~% A = B is ~a" (= a b)) 
(format t "~% A /= B is ~a" (/= a b)) 
(format t "~% A > B is ~a" (> a b)) 
(format t "~% A < B is ~a" (< a b)) 
(format t "~% A >= B is ~a" (>= a b)) 
(format t "~% A <= B is ~a" (<= a b)) 
(format t "~% Max of A and B is ~d" (max a b)) 
(format t "~% Min of A and B is ~d" (min a b)) 
